### ISSUE TITLE
Keep templates when writing config files

### ISSUE THREAD

**Issue by Hipska** [oisis/docker-collectd#2]
please add the` --keep-template` argument to the `envtpl` command, so ENV var changes are reflected in the config files.

**Comment by oisis** [comment]
Hi,
 Thanks for reporting. Will take care about it probably tomorrow.

**Comment by oisis** [comment]
Done. Please test it and let me know if note is OK.

**Comment by Hipska** [comment]
The code in commit 24f5d63 looks good, I'm not able to test right now.

Thanks.
