### ISSUE TITLE
Align env variables

### ISSUE THREAD

**Issue by Hipska** [oisis/docker-collectd#3]
The run script looks for GRAPHITE_HOST while the write_graphite template uses GRAPHITE_ADDR.

The same applies for other templates.

**Comment by oisis** [comment]
Hi,
 Will fix it very soon. Thanks for reporting.

**Comment by oisis** [comment]
Fixed. Please test it and let me know if it's OK now.

**Comment by Hipska** [comment]
It also applies to the InfluxDB template and the readme file needs to be adapted. But thanks for the quick fix.

**Comment by oisis** [comment]
Yes, that is true. I messed with variable names a bit when I was changing templates before initial commit. I hope now everything is cleaned up. Also new build for docker hub should be ready very sun.

**Comment by Hipska** [comment]
Please reopen, OpenTSDB is still not aligned..

**Comment by oisis** [comment]
I think it is. Fixed it before. Please pull, check and let me know.

**Comment by Hipska** [comment]
No, please see [scripts/run.sh#L13](https://github.com/oisis/docker-collectd/blob/master/scripts/run.sh#L13), it still uses `$OPENTSDB_ADDR`.

**Comment by oisis** [comment]
That is right, I missed that one. Now is done. Thanks for reporting.
